---
- name: Initial Web Server Provisioning
  hosts: web
  remote_user: root

  tasks:
  - name: Update and upgrade all apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 # One Day

  - name: Install various packages using apt
    apt:
      name:
        - nginx
        - git
        - vim
      state: latest

  - name: make .bashrc colorful and add ll alias
    copy:
      dest: ~/.bashrc
      content: |
        export LS_OPTIONS='--color=auto' 
        eval "$(dircolors)"
        alias ls='ls $LS_OPTIONS'
        alias ll='ls $LS_OPTIONS -laph'

  - name: Disallow SSH password authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
      state: present
      validate: sshd -t -f %s

  - name: Restart sshd
    service:
      name: sshd
      state: restarted

  - name: Download zola web installer
    ansible.builtin.get_url:
      url: https://github.com/barnumbirr/zola-debian/releases/download/v0.17.2-1/zola_0.17.2-1_amd64_bullseye.deb
      dest: ~/zola_installer.deb

  - name: Install zola SSB
    apt:
      deb: ~/zola_installer.deb

  - name: Clone Website Repository
    ansible.builtin.git:
      repo: https://github.com/kiyoshigawa/twa.ninja
      dest: ~/twa.ninja/

  - name: building website using zola
    ansible.builtin.command:
      chdir: ~/twa.ninja/website
      cmd: zola build
