version: '3'

services:
  twa_ninja:
    network_mode: "host"
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /home/tim/twa.ninja:/srv
      - /home/tim/nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf
