# The URL the site will be built for
base_url = "https://twa.ninja"

title = "twa.ninja - The Personal Website of Tim Anderson"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown.highlighting]
theme = "one-dark-pro"
style = "inline"

[slugify]
paths = "off"
taxonomies = "off"
anchors = "off"

[extra]
# Put all your custom variables here
